// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: server.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BatchMetricHandler_SaveBatchMetrics_FullMethodName = "/server.BatchMetricHandler/SaveBatchMetrics"
	BatchMetricHandler_GetJSONMetric_FullMethodName    = "/server.BatchMetricHandler/GetJSONMetric"
)

// BatchMetricHandlerClient is the client API for BatchMetricHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BatchMetricHandlerClient interface {
	SaveBatchMetrics(ctx context.Context, in *BatchMetricRequest, opts ...grpc.CallOption) (*BatchMetricResponse, error)
	GetJSONMetric(ctx context.Context, in *GetJSONMetricsRequest, opts ...grpc.CallOption) (*GetJSONMetricResponse, error)
}

type batchMetricHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewBatchMetricHandlerClient(cc grpc.ClientConnInterface) BatchMetricHandlerClient {
	return &batchMetricHandlerClient{cc}
}

func (c *batchMetricHandlerClient) SaveBatchMetrics(ctx context.Context, in *BatchMetricRequest, opts ...grpc.CallOption) (*BatchMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchMetricResponse)
	err := c.cc.Invoke(ctx, BatchMetricHandler_SaveBatchMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batchMetricHandlerClient) GetJSONMetric(ctx context.Context, in *GetJSONMetricsRequest, opts ...grpc.CallOption) (*GetJSONMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJSONMetricResponse)
	err := c.cc.Invoke(ctx, BatchMetricHandler_GetJSONMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatchMetricHandlerServer is the server API for BatchMetricHandler service.
// All implementations must embed UnimplementedBatchMetricHandlerServer
// for forward compatibility.
type BatchMetricHandlerServer interface {
	SaveBatchMetrics(context.Context, *BatchMetricRequest) (*BatchMetricResponse, error)
	GetJSONMetric(context.Context, *GetJSONMetricsRequest) (*GetJSONMetricResponse, error)
	mustEmbedUnimplementedBatchMetricHandlerServer()
}

// UnimplementedBatchMetricHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBatchMetricHandlerServer struct{}

func (UnimplementedBatchMetricHandlerServer) SaveBatchMetrics(context.Context, *BatchMetricRequest) (*BatchMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveBatchMetrics not implemented")
}
func (UnimplementedBatchMetricHandlerServer) GetJSONMetric(context.Context, *GetJSONMetricsRequest) (*GetJSONMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJSONMetric not implemented")
}
func (UnimplementedBatchMetricHandlerServer) mustEmbedUnimplementedBatchMetricHandlerServer() {}
func (UnimplementedBatchMetricHandlerServer) testEmbeddedByValue()                            {}

// UnsafeBatchMetricHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchMetricHandlerServer will
// result in compilation errors.
type UnsafeBatchMetricHandlerServer interface {
	mustEmbedUnimplementedBatchMetricHandlerServer()
}

func RegisterBatchMetricHandlerServer(s grpc.ServiceRegistrar, srv BatchMetricHandlerServer) {
	// If the following call pancis, it indicates UnimplementedBatchMetricHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BatchMetricHandler_ServiceDesc, srv)
}

func _BatchMetricHandler_SaveBatchMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchMetricHandlerServer).SaveBatchMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchMetricHandler_SaveBatchMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchMetricHandlerServer).SaveBatchMetrics(ctx, req.(*BatchMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BatchMetricHandler_GetJSONMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJSONMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchMetricHandlerServer).GetJSONMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchMetricHandler_GetJSONMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchMetricHandlerServer).GetJSONMetric(ctx, req.(*GetJSONMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BatchMetricHandler_ServiceDesc is the grpc.ServiceDesc for BatchMetricHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchMetricHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.BatchMetricHandler",
	HandlerType: (*BatchMetricHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveBatchMetrics",
			Handler:    _BatchMetricHandler_SaveBatchMetrics_Handler,
		},
		{
			MethodName: "GetJSONMetric",
			Handler:    _BatchMetricHandler_GetJSONMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
