// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OK    Status = 0
	Status_ERROR Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type MemStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gauge         map[string]float64     `protobuf:"bytes,1,rep,name=gauge,proto3" json:"gauge,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`    // gauge метрики
	Counter       map[string]int64       `protobuf:"bytes,2,rep,name=counter,proto3" json:"counter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // counter метрики
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemStorage) Reset() {
	*x = MemStorage{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemStorage) ProtoMessage() {}

func (x *MemStorage) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemStorage.ProtoReflect.Descriptor instead.
func (*MemStorage) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *MemStorage) GetGauge() map[string]float64 {
	if x != nil {
		return x.Gauge
	}
	return nil
}

func (x *MemStorage) GetCounter() map[string]int64 {
	if x != nil {
		return x.Counter
	}
	return nil
}

type SyncInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Db             string                 `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`                                                  // строка подключения к базе данных
	File           string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`                                              // путь до файла для сохранения метрик
	TustedSubnet   string                 `protobuf:"bytes,3,opt,name=tusted_subnet,json=tustedSubnet,proto3" json:"tusted_subnet,omitempty"`          // доверенная подсеть
	SyncFileRecord bool                   `protobuf:"varint,4,opt,name=sync_file_record,json=syncFileRecord,proto3" json:"sync_file_record,omitempty"` // атрибут определяющий, следует ли немедленно сохранять присланные метрики
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncInfo) Reset() {
	*x = SyncInfo{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInfo) ProtoMessage() {}

func (x *SyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInfo.ProtoReflect.Descriptor instead.
func (*SyncInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *SyncInfo) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *SyncInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SyncInfo) GetTustedSubnet() string {
	if x != nil {
		return x.TustedSubnet
	}
	return ""
}

func (x *SyncInfo) GetSyncFileRecord() bool {
	if x != nil {
		return x.SyncFileRecord
	}
	return false
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         int64                  `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`             // изменение метики counter
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`            // значение метрики gauge
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`                    // название метрики
	MType         string                 `protobuf:"bytes,4,opt,name=m_type,json=mType,proto3" json:"m_type,omitempty"` // тип метрики
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetMType() string {
	if x != nil {
		return x.MType
	}
	return ""
}

type HandlersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Storage       *MemStorage            `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	SyncConfig    *SyncInfo              `protobuf:"bytes,2,opt,name=sync_config,json=syncConfig,proto3" json:"sync_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlersInput) Reset() {
	*x = HandlersInput{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlersInput) ProtoMessage() {}

func (x *HandlersInput) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlersInput.ProtoReflect.Descriptor instead.
func (*HandlersInput) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *HandlersInput) GetStorage() *MemStorage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *HandlersInput) GetSyncConfig() *SyncInfo {
	if x != nil {
		return x.SyncConfig
	}
	return nil
}

type BatchMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMetricRequest) Reset() {
	*x = BatchMetricRequest{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMetricRequest) ProtoMessage() {}

func (x *BatchMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMetricRequest.ProtoReflect.Descriptor instead.
func (*BatchMetricRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *BatchMetricRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetJSONMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // название метрики
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJSONMetricsRequest) Reset() {
	*x = GetJSONMetricsRequest{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJSONMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJSONMetricsRequest) ProtoMessage() {}

func (x *GetJSONMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJSONMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetJSONMetricsRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetJSONMetricsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BatchMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=server.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMetricResponse) Reset() {
	*x = BatchMetricResponse{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMetricResponse) ProtoMessage() {}

func (x *BatchMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMetricResponse.ProtoReflect.Descriptor instead.
func (*BatchMetricResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *BatchMetricResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

type GetJSONMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJSONMetricResponse) Reset() {
	*x = GetJSONMetricResponse{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJSONMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJSONMetricResponse) ProtoMessage() {}

func (x *GetJSONMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJSONMetricResponse.ProtoReflect.Descriptor instead.
func (*GetJSONMetricResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetJSONMetricResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x06server\"\xf2\x01\n" +
	"\n" +
	"MemStorage\x123\n" +
	"\x05gauge\x18\x01 \x03(\v2\x1d.server.MemStorage.GaugeEntryR\x05gauge\x129\n" +
	"\acounter\x18\x02 \x03(\v2\x1f.server.MemStorage.CounterEntryR\acounter\x1a8\n" +
	"\n" +
	"GaugeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a:\n" +
	"\fCounterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"}\n" +
	"\bSyncInfo\x12\x0e\n" +
	"\x02db\x18\x01 \x01(\tR\x02db\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12#\n" +
	"\rtusted_subnet\x18\x03 \x01(\tR\ftustedSubnet\x12(\n" +
	"\x10sync_file_record\x18\x04 \x01(\bR\x0esyncFileRecord\"[\n" +
	"\x06Metric\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x15\n" +
	"\x06m_type\x18\x04 \x01(\tR\x05mType\"p\n" +
	"\rHandlersInput\x12,\n" +
	"\astorage\x18\x01 \x01(\v2\x12.server.MemStorageR\astorage\x121\n" +
	"\vsync_config\x18\x02 \x01(\v2\x10.server.SyncInfoR\n" +
	"syncConfig\">\n" +
	"\x12BatchMetricRequest\x12(\n" +
	"\ametrics\x18\x01 \x03(\v2\x0e.server.MetricR\ametrics\"'\n" +
	"\x15GetJSONMetricsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x13BatchMetricResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.server.StatusR\x06status\"?\n" +
	"\x15GetJSONMetricResponse\x12&\n" +
	"\x06metric\x18\x01 \x01(\v2\x0e.server.MetricR\x06metric*\x1b\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x012\xb0\x01\n" +
	"\x12BatchMetricHandler\x12K\n" +
	"\x10SaveBatchMetrics\x12\x1a.server.BatchMetricRequest\x1a\x1b.server.BatchMetricResponse\x12M\n" +
	"\rGetJSONMetric\x12\x1d.server.GetJSONMetricsRequest\x1a\x1d.server.GetJSONMetricResponseB\x11Z\x0finternal/serverb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_server_proto_goTypes = []any{
	(Status)(0),                   // 0: server.Status
	(*MemStorage)(nil),            // 1: server.MemStorage
	(*SyncInfo)(nil),              // 2: server.SyncInfo
	(*Metric)(nil),                // 3: server.Metric
	(*HandlersInput)(nil),         // 4: server.HandlersInput
	(*BatchMetricRequest)(nil),    // 5: server.BatchMetricRequest
	(*GetJSONMetricsRequest)(nil), // 6: server.GetJSONMetricsRequest
	(*BatchMetricResponse)(nil),   // 7: server.BatchMetricResponse
	(*GetJSONMetricResponse)(nil), // 8: server.GetJSONMetricResponse
	nil,                           // 9: server.MemStorage.GaugeEntry
	nil,                           // 10: server.MemStorage.CounterEntry
}
var file_server_proto_depIdxs = []int32{
	9,  // 0: server.MemStorage.gauge:type_name -> server.MemStorage.GaugeEntry
	10, // 1: server.MemStorage.counter:type_name -> server.MemStorage.CounterEntry
	1,  // 2: server.HandlersInput.storage:type_name -> server.MemStorage
	2,  // 3: server.HandlersInput.sync_config:type_name -> server.SyncInfo
	3,  // 4: server.BatchMetricRequest.metrics:type_name -> server.Metric
	0,  // 5: server.BatchMetricResponse.status:type_name -> server.Status
	3,  // 6: server.GetJSONMetricResponse.metric:type_name -> server.Metric
	5,  // 7: server.BatchMetricHandler.SaveBatchMetrics:input_type -> server.BatchMetricRequest
	6,  // 8: server.BatchMetricHandler.GetJSONMetric:input_type -> server.GetJSONMetricsRequest
	7,  // 9: server.BatchMetricHandler.SaveBatchMetrics:output_type -> server.BatchMetricResponse
	8,  // 10: server.BatchMetricHandler.GetJSONMetric:output_type -> server.GetJSONMetricResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
